name: 'Provenance / SBOM / Sign'

description: 'Creates SBOM & provenance files and signs the image'

inputs:
  image-name:
    description: "name of the image"
    required: true
    default: ''
  image-tag:
    description: "image tag"
    required: true
    default: ""

runs:
  using: "composite"

  steps:

    - name: Install cosign
      uses: sigstore/cosign-installer@v2
      with:
        cosign-release: v1.13.6

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@v0.7.0

    - name: Check Cosign install
      shell: bash
      run: cosign version

    - name: Login to ghcr.io
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod

    - name: Set up crane
      shell: bash
      run: go install github.com/google/go-containerregistry/cmd/crane@v0.11.0

    - name: Get docker image tag
      id: container_info
      shell: bash
      run: echo "digest=$(crane digest ${INPUTS_IMAGE_NAME}:${INPUTS_IMAGE_TAG})" >> $GITHUB_OUTPUT
      env:
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        INPUTS_IMAGE_TAG: ${{ inputs.image-tag }}

    - name: Sign image
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: "1"
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        STEPS_CONTAINER_INFO_OUTPUTS_DIGEST: ${{ steps.container_info.outputs.digest }}
      run: cosign sign -a GITHUB_ACTOR=${GITHUB_TRIGGERING_ACTOR} "${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST}"

    - name: Attach SBOM to image
      shell: bash
      id: sbom
      env:
        COSIGN_EXPERIMENTAL: "1"
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        STEPS_CONTAINER_INFO_OUTPUTS_DIGEST: ${{ steps.container_info.outputs.digest }}
        INPUTS_IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        # Image SBOM (OS + application libs contained in the image)
        syft "${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST}" -o spdx-json=sbom.${INPUTS_IMAGE_TAG}.spdx.json
        cosign attest --predicate sbom.${INPUTS_IMAGE_TAG}.spdx.json --type spdx "${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST}"
        cosign verify-attestation --type spdx ${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST} | jq '.payload |= @base64d | .payload | fromjson'

        # Go modules SBOM (dependencies from the source tree)
        # Requires repository to be checked out before this composite action runs.
        syft dir:. -o spdx-json=sbom.gomod.${INPUTS_IMAGE_TAG}.spdx.json
        cosign attest --predicate sbom.gomod.${INPUTS_IMAGE_TAG}.spdx.json --type spdx "${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST}"
        cosign verify-attestation --type spdx ${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST} | jq '.payload |= @base64d | .payload | fromjson'

    - name: Generate provenance
      uses: philips-labs/slsa-provenance-action@v0.7.2
      with:
        command: generate
        subcommand: container
        arguments: --repository "${{ inputs.image-name }}" --output-path provenance.${{ inputs.image-tag }}.intoto.jsonl --digest "${{ steps.container_info.outputs.digest }}" --tags "${{ inputs.image-tag }}"
      env:
        COSIGN_EXPERIMENTAL: "0"
        GITHUB_TOKEN: "${{ github.token }}"

    - name: Attach provenance
      shell: bash
      id: provenance
      env:
        COSIGN_EXPERIMENTAL: "1"
        INPUTS_IMAGE_TAG: ${{ inputs.image-tag }}
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        STEPS_CONTAINER_INFO_OUTPUTS_DIGEST: ${{ steps.container_info.outputs.digest }}
      run: |
        jq '.predicate' provenance.${INPUTS_IMAGE_TAG}.intoto.jsonl > provenance-predicate.att
        cosign attest --predicate provenance-predicate.att --type slsaprovenance "${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST}"
        cosign verify-attestation --type slsaprovenance ${INPUTS_IMAGE_NAME}@${STEPS_CONTAINER_INFO_OUTPUTS_DIGEST}
